### ISSUE TITLE
모바일에서의 가독성 확보.

### ISSUE THREAD

**Issue by jeaimetu** [jeaimetu/dwitter#17]
모바일(스마트폰)에서 접속 할 경우 좌우 여백 제거하여 글 가독성 확보

이 아이템은 일단 holding으로 놓고, 이후에 design과논의하면 어떨지요? 전 지금 모양도 나쁘지 않아서요,
우선 순위도 모바일이니 일단은 조금 낫게 하는 것이 좋겠습니다.

**Comment by KimDaeHyung** [comment]
1차 수정완료.
