### ISSUE TITLE
글밥이 많은 경우의 처리.

### ISSUE THREAD

**Issue by jeaimetu** [jeaimetu/dwitter#18]
글내용에 줄내림(enter key)가 많을 경우 툴팁(말풍선) 또는 슬라이드(스르륵내려가며 전체내용 보임) 기능 구현

-> 디테일 뷰 창으로 팝업을 띠우거나 화면 전환하는 것이 어떨까요? 위의 방법을 구현을 해도 모바일 사용성이 좋지 않고, 툴팁은 보통 요약을 보여주는 UX로 알고 있어서요..(모바일에선 그런데요..Web쪽은 반대일지도..) 정확히 어떤 모양인지 잘 감이 안오는데요..

비슷하게 구현된 사이트가 있을까요?

**Comment by KimDaeHyung** [comment]
프로토 타입 만들어서 보여드리겠습니다~

**Comment by KimDaeHyung** [comment]
프로토 타입 완료. 및 close
