### ISSUE TITLE
EOS account 지정하는 메뉴 구현.

### ISSUE THREAD

**Issue by jeaimetu** [jeaimetu/dwitter#20]
1. Frontend에 EOS account설정하는 메뉴 구현. 현재는 ERC20 base로 되어 있음.
2. Backend에 이를 저장하고,, wallet정보를 요청할때 return하는 기능 구현

**Comment by KimDaeHyung** [comment]
1. frontend ERC20 base 에서 EOS Account 변경 완료.
2. backend interface 대기중.
3. prototype 디자인 적용중

**Comment by jeaimetu** [comment]
API와 DB구조 결정 및 password암호화로 시간이 걸렸음.
금일 API 만들 예정임.!

**Comment by jeaimetu** [comment]
쏴리!

**Comment by jeaimetu** [comment]
**EOS account지정 :** 
setwallet
parameter : account
return : OK or fail

**EOS account를 읽어갈때 :** 
기존의 readwallet을 변경..기존에는 wallet의 DAB 토큰 개수만 return했으나, 다음과 같이 추가로
DAB토큰 개수와 함께 EOS account를 같이 return

**기존**
		  var body = {
			  "result": "done",
			  "balance" : result
	  	  };

**변경**

		  var body = {
			  "result": "done",
			  "balance" : result,
			  "**account**" : result2
	  	  };

그리고 기존에는 result에 done이 올라갔는데요..이를 다른 것에 맞추었습니다.
제대로 읽었으면 result 가 OK, account설정 전이거나 없으면 "fail"

입니다.
