### ISSUE TITLE
보팅 버튼 동작 개선 요청.

### ISSUE THREAD

**Issue by jeaimetu** [jeaimetu/dwitter#23]
글이 A, B, C가 있을때, A의 voting을 누르면 B,C도 같이 깜빡입니다. 해당 글만 깜빡이게 할수는 없을지요?
감사합니다.

**Comment by KimDaeHyung** [comment]
수정하겠습니다 핡핡~

**Comment by KimDaeHyung** [comment]
수정 완료하였습니다 핡핡~
