### ISSUE TITLE
지갑화면 신규 design

### ISSUE THREAD

**Issue by jeaimetu** [jeaimetu/dwitter#44]
데블 내의 지갑.
데블 외부의 지갑(EOS지갑)을 구분하고, 이 지갑간의 인출 기능을 추가.

데블에서 활동을 하면 데블 내의 지갑에 DAB이 쌓임.
일정 시점에 인출을 누르면 데블 내의 지갑은 0이되고, 외부 지갑으로 DAB이 옮겨감.
이때 잔액 조회를 하면 옮겨간 DAB만큼 추가로 보임.

끝.

**Comment by xogns520** [comment]
https://zpl.io/VDn7RQv

**Comment by jeaimetu** [comment]
신규 지갑과 관련된 API
getbalance : EOS계정과 연결된, 외부 지갑에 있는 balance를 조회함. (계정이 없으면 API가 call되지 않게 해주세요.)

transferbalance : 내부 지갑에 있는 DAB을 EOS계정으로 전송. 성공하면 success, 실패하면 fail.
이것도 계정이 없으면 call되지 않게 해주세요.
