### ISSUE TITLE
동일한 아이디 가입이슈

### ISSUE THREAD

**Issue by xogns520** [jeaimetu/dwitter#51]
동일한 아이디 가입시 가입이완료되었습니다. -> ID / PW를 확인해주세요. 순으로 팝업이 뜹니다.

이미 있는 ID 입니다. 다른 ID를 입력해주세요. <- 이렇게 팝업내용이 나오도록 수정이 필요합니다.

**Comment by jeaimetu** [comment]
수정완료. return값이 duplicated를 가지도록 제대로 수정했습니다.
